### ISSUE TITLE
Fails on import

### ISSUE THREAD

**Issue by ianfoo** [faiface/generics#2] opened 2019-06-28 21:24 UTC
Unfortunately, I cannot follow the example as shown in the README. It fails when it encounters the `import "fmt"` line. I've tried it on macOS 10.13.6 (High Sierra) and Debian (testing/10). Here's the output.
```
[ian@ianbook tmp] $ cat reverse.go
// reverse.go

package main

import "fmt"

func Reverse(a []type T) {
    for i, j := 0, len(a)-1; i < j; i, j = i+1, j-1 {
        a[i], a[j] = a[j], a[i]
    }
}

func main() {
    a := []int{1, 2, 3, 4, 5}
    b := []string{"A", "B", "C"}
    Reverse(a)
    Reverse(b)
    fmt.Println(a)
    fmt.Println(b)
}
[ian@ianbook tmp] $ generics -out out.go -debug reverse.go
reverse.go:5:8: could not import fmt (cannot import, possibly version skew (unknown export format version -1 ("i\x00\x9e\x1b\xde2\x18$GOROOT/src/fmt/print.go\x00\x05Write\x01b\x01n\x03err\x05Width\x03wid\x02ok\tPrecision\x04prec\x04Flag\x01c\x06Format\x01f\x05State\x06String\bGoString\x01w\x06Writer\x02io\x06format\x01a\aesc:0x1\aesc:0x9\aFprintf\x06Stdout\x02os\x03New\x06errors\aSprintf\x06Fprint\bFprintln\x17$GOROOT/src/fmt/scan.go\bReadRune\x01r\x04size")) - reinstall package)
[ian@ianbook tmp] $ go version
go version go1.12.6 darwin/amd64
[ian@ianbook tmp] $ uname -a
Darwin ianbook.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64
```
If I remove the import and use the builtin `println`, I get the same panic that is described in #1 (also on both macOS and Linux).
```
[ian@ianbook tmp] $ cat reverse.go
// reverse.go

package main

func Reverse(a []type T) {
    for i, j := 0, len(a)-1; i < j; i, j = i+1, j-1 {
        a[i], a[j] = a[j], a[i]
    }
}

func main() {
    a := []int{1, 2, 3, 4, 5}
    b := []string{"A", "B", "C"}
    Reverse(a)
    Reverse(b)
    println(a)
    println(b)
}
[ian@ianbook tmp] $ generics -out out.go -debug reverse.go
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1170097]

goroutine 1 [running]:
github.com/faiface/generics/go/types.(*Checker).handleBailout(0xc000118000, 0xc00012bd90)
	/Users/ian/src/github.com/faiface/generics/go/types/check.go:225 +0x98
panic(0x12665e0, 0x14b2ef0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/faiface/generics/go/types.(*Checker).assignment(0xc000118000, 0x0, 0xc0000bf4c0, 0x0, 0x0, 0xc0000c01c0, 0x13)
	/Users/ian/src/github.com/faiface/generics/go/types/assignments.go:44 +0x77
github.com/faiface/generics/go/types.(*Checker).builtin(0xc000118000, 0xc0000bf4c0, 0xc0000be740, 0xc, 0xc00009c600)
	/Users/ian/src/github.com/faiface/generics/go/types/builtins.go:493 +0x451e
github.com/faiface/generics/go/types.(*Checker).call(0xc000118000, 0xc0000bf4c0, 0xc0000be740, 0x2)
	/Users/ian/src/github.com/faiface/generics/go/types/call.go:182 +0xbba
github.com/faiface/generics/go/types.(*Checker).exprInternal(0xc000118000, 0xc0000bf4c0, 0x13044a0, 0xc0000be740, 0x0, 0x0, 0x155fd98)
	/Users/ian/src/github.com/faiface/generics/go/types/expr.go:1450 +0x1f13
github.com/faiface/generics/go/types.(*Checker).rawExpr(0xc000118000, 0xc0000bf4c0, 0x13044a0, 0xc0000be740, 0x0, 0x0, 0x2)
	/Users/ian/src/github.com/faiface/generics/go/types/expr.go:975 +0x81
github.com/faiface/generics/go/types.(*Checker).stmt(0xc000118000, 0x0, 0x13046e0, 0xc0000a05a0)
	/Users/ian/src/github.com/faiface/generics/go/types/stmt.go:331 +0x4426
github.com/faiface/generics/go/types.(*Checker).stmtList(0xc000118000, 0x0, 0xc0000c2280, 0x6, 0x8)
	/Users/ian/src/github.com/faiface/generics/go/types/stmt.go:123 +0xd1
github.com/faiface/generics/go/types.(*Checker).funcBody(0xc000118000, 0xc0000ec2a0, 0xc0000bc330, 0x4, 0xc00009c660, 0xc0000a2ba0)
	/Users/ian/src/github.com/faiface/generics/go/types/stmt.go:43 +0x169
github.com/faiface/generics/go/types.(*Checker).functionBodies(0xc000118000)
	/Users/ian/src/github.com/faiface/generics/go/types/resolver.go:486 +0xe8
github.com/faiface/generics/go/types.(*Checker).checkFiles(0xc000118000, 0xc0000dbf00, 0x1, 0x1, 0x0, 0x0)
	/Users/ian/src/github.com/faiface/generics/go/types/check.go:241 +0xc1
github.com/faiface/generics/go/types.(*Checker).Files(...)
	/Users/ian/src/github.com/faiface/generics/go/types/check.go:230
github.com/faiface/generics/go/types.(*Config).Check(0xc0000be840, 0x0, 0x0, 0xc0000be300, 0xc0000dbf00, 0x1, 0x1, 0xc00009c5a0, 0x0, 0xc0000dbec0, ...)
	/Users/ian/src/github.com/faiface/generics/go/types/api.go:359 +0x11c
main.main()
	/Users/ian/src/github.com/faiface/generics/main.go:62 +0x2a0
```

**Comment by faiface** [comment] 2019-06-29 00:30
I'm sorry this is happening. I believe (but not yet confirmed) the issue is that I copied the `"go/*"` packages from Go 1.10 and the importing probably doesn't work on newer Go.

Here what I think you need to do:
1. Replace the `go/internal` directory in this repo by your local `$GOROOT/src/go/internal` directory.
2. Rename all occurrences (in imports) of `"go/internal` with `"github.com/faiface/generics/go/internal`.

Please, try this and tell me how it goes! I'm really curious to see if this fixes it.

**Comment by faiface** [comment] 2019-06-29 05:09
Sorry, closed accidentally.

**Comment by faiface** [comment] 2019-06-29 22:12
Okay, I think I may have fixed the problem. Please pull my changes and try if it works.

**Comment by faiface** [comment] 2019-07-01 11:56
ping

**Comment by faiface** [comment] 2019-07-02 10:01
Okay, I'm closing this issue, because other people have confirmed the fix. If it doesn't work for you, feel free to reopen this issue.

**Closed as completed by faiface** 2019-07-02 10:01 UTC
Labels: bug
